# Generated by Django 4.0.4 on 2022-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование технологии')),
                ('image', models.FileField(upload_to='techs/', verbose_name='Изображение технологии')),
                ('about', models.CharField(max_length=250, verbose_name='О технологии')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование технологии')),
                ('itis', models.CharField(choices=[('1', 'Сайт'), ('2', 'Дизайн')], max_length=300, verbose_name='Вид работы')),
                ('image', models.FileField(upload_to='works/', verbose_name='Изображение')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пример работы',
                'verbose_name_plural': 'Примеры работ',
                'ordering': ['-id'],
            },
        ),
    ]
