# Generated by Django 4.0.4 on 2022-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_technologies_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('cost', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цены услуги',
                'verbose_name_plural': 'Цены услуг',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='about',
            field=models.TextField(max_length=350, verbose_name='О услуге'),
        ),
        migrations.AlterField(
            model_name='servicesdop',
            name='about',
            field=models.TextField(max_length=250, verbose_name='О услуге'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='about',
            field=models.TextField(max_length=350, verbose_name='О технологии'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='image',
            field=models.ImageField(upload_to='techs/', verbose_name='Изображение технологии'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.ImageField(upload_to='works/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='works',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
