# Generated by Django 4.0.4 on 2022-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_calculate_alter_services_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
